In [2]:
import pandas as pd
import numpy as np

In [34]:
draft = 'C:/Users/Enzo/OneDrive/Escritorio/Henry PF/csv/draft_history.csv'
df = pd.read_csv(draft, low_memory=True)

In [35]:
df.tail()

,person_id,player_name,season,round_number,round_pick,overall_pick,draft_type,team_id,team_city,team_name,team_abbreviation,organization,organization_type,player_profile_flag
7985,1641771,Jalen Slawson,2023,2,24,54,Draft,1610612758,Sacramento,Kings,SAC,Furman,College/University,1
7986,1631209,Isaiah Wong,2023,2,25,55,Draft,1610612754,Indiana,Pacers,IND,Miami (FL),College/University,1
7987,1641844,Tarik Biberovic,2023,2,26,56,Draft,1610612763,Memphis,Grizzlies,MEM,Fenerbahce S.K. (Turkey),Other Team/Club,1
7988,1631218,Trayce Jackson-Davis,2023,2,27,57,Draft,1610612764,Washington,Wizards,WAS,Indiana,College/University,1
7989,1641753,Chris Livingston,2023,2,28,58,Draft,1610612749,Milwaukee,Bucks,MIL,Kentucky,College/University,1

In [36]:
df = df.drop(columns=['team_city', 'team_abbreviation', 'team_name' ])

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7990 entries, 0 to 7989
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   person_id            7990 non-null   int64
 1   player_name          7990 non-null   object
 2   season               7990 non-null   int64
 3   round_number         7990 non-null   int64
 4   round_pick           7990 non-null   int64
 5   overall_pick         7990 non-null   int64
 6   draft_type           7990 non-null   object
 7   team_id              7990 non-null   int64
 8   organization         7971 non-null   object
 9   organization_type    7971 non-null   object
 10  player_profile_flag  7990 non-null   int64
dtypes: int64(7), object(4)
memory usage: 686.8+ KB

In [30]:
df_sin_duplicados = df.drop_duplicates(subset='person_id', keep='first')

In [31]:
ruta_guardado = "draft_history_listo.csv" 
df_sin_duplicados.to_csv(ruta_guardado, index=False)

In [3]:
draft = 'C:/Users/Enzo/OneDrive/Escritorio/Henry PF/csv/draft_combine_stats.csv'
df = pd.read_csv(draft, low_memory=True)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1202 entries, 0 to 1201
Data columns (total 47 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   season                        1202 non-null   int64
 1   player_id                     1202 non-null   int64
 2   first_name                    1202 non-null   object
 3   last_name                     1202 non-null   object
 4   player_name                   1202 non-null   object
 5   position                      1197 non-null   object
 6   height_wo_shoes               1153 non-null   float64
 7   height_wo_shoes_ft_in         1153 non-null   object
 8   height_w_shoes                1008 non-null   float64
 9   height_w_shoes_ft_in          1008 non-null   object
 10  weight                        1152 non-null   float64
 11  wingspan                      1153 non-null   float64
 12  wingspan_ft_in                1153 non-null   object
 13  standing_reach                1152 non-null   float64
 14  standing_reach_ft_in          1152 non-null   object
 15  body_fat_pct                  1003 non-null   float64
 16  hand_length                   719 non-null    float64
 17  hand_width                    719 non-null    float64
 18  standing_vertical_leap        1017 non-null   float64
 19  max_vertical_leap             1017 non-null   float64
 20  lane_agility_time             1008 non-null   float64
 21  modified_lane_agility_time    411 non-null    float64
 22  three_quarter_sprint          1012 non-null   float64
 23  bench_press                   808 non-null    float64
 24  spot_fifteen_corner_left      74 non-null     object
 25  spot_fifteen_break_left       76 non-null     object
 26  spot_fifteen_top_key          76 non-null     object
 27  spot_fifteen_break_right      76 non-null     object
 28  spot_fifteen_corner_right     76 non-null     object
 29  spot_college_corner_left      245 non-null    object
 30  spot_college_break_left       166 non-null    object
 31  spot_college_top_key          166 non-null    object
 32  spot_college_break_right      166 non-null    object
 33  spot_college_corner_right     166 non-null    object
 34  spot_nba_corner_left          217 non-null    object
 35  spot_nba_break_left           217 non-null    object
 36  spot_nba_top_key              217 non-null    object
 37  spot_nba_break_right          217 non-null    object
 38  spot_nba_corner_right         217 non-null    object
 39  off_drib_fifteen_break_left   166 non-null    object
 40  off_drib_fifteen_top_key      166 non-null    object
 41  off_drib_fifteen_break_right  166 non-null    object
 42  off_drib_college_break_left   110 non-null    object
 43  off_drib_college_top_key      31 non-null     object
 44  off_drib_college_break_right  31 non-null     object
 45  on_move_fifteen               148 non-null    object
 46  on_move_college               116 non-null    object
dtypes: float64(14), int64(2), object(31)
memory usage: 441.5+ KB

In [5]:
missingData = df.isnull().mean() * 100
print(missingData[missingData > 0].sort_values(ascending=False))

off_drib_college_top_key        97.420965
off_drib_college_break_right    97.420965
spot_fifteen_corner_left        93.843594
spot_fifteen_break_right        93.677205
spot_fifteen_top_key            93.677205
spot_fifteen_corner_right       93.677205
spot_fifteen_break_left         93.677205
off_drib_college_break_left     90.848586
on_move_college                 90.349418
on_move_fifteen                 87.687188
off_drib_fifteen_top_key        86.189684
spot_college_break_left         86.189684
spot_college_top_key            86.189684
spot_college_corner_right       86.189684
spot_college_break_right        86.189684
off_drib_fifteen_break_left     86.189684
off_drib_fifteen_break_right    86.189684
spot_nba_break_right            81.946755
spot_nba_top_key                81.946755
spot_nba_break_left             81.946755
spot_nba_corner_left            81.946755
spot_nba_corner_right           81.946755
spot_college_corner_left        79.617304
modified_lane_agility_time      65.806988
hand_width                      40.183028
hand_length                     40.183028
bench_press                     32.778702
body_fat_pct                    16.555740
height_w_shoes                  16.139767
height_w_shoes_ft_in            16.139767
lane_agility_time               16.139767
three_quarter_sprint            15.806988
standing_vertical_leap          15.391015
max_vertical_leap               15.391015
standing_reach_ft_in             4.159734
weight                           4.159734
standing_reach                   4.159734
height_wo_shoes                  4.076539
height_wo_shoes_ft_in            4.076539
wingspan                         4.076539
wingspan_ft_in                   4.076539
position                         0.415973
dtype: float64

In [6]:
#Eliminamos las columnas que no vamos a utilizar
dfEliminados = df.drop(["first_name", "last_name", "height_wo_shoes", "height_wo_shoes_ft_in", "height_w_shoes", "height_w_shoes_ft_in", "wingspan", "wingspan_ft_in", "standing_reach", "standing_reach_ft_in", "body_fat_pct", "hand_length", "hand_width", "modified_lane_agility_time", "bench_press", "spot_fifteen_corner_left", "spot_fifteen_break_left", "spot_fifteen_top_key", "spot_fifteen_break_right", "spot_fifteen_corner_right", "spot_college_corner_left", "spot_college_break_left", "spot_college_top_key", "spot_college_break_right", "spot_college_corner_right", "spot_nba_corner_left", "spot_nba_break_left", "spot_nba_top_key", "spot_nba_break_right", "spot_nba_corner_right", "off_drib_fifteen_break_left", "off_drib_fifteen_top_key", "off_drib_fifteen_break_right", "off_drib_college_break_left", "off_drib_college_top_key", "off_drib_college_break_right", "on_move_fifteen", "on_move_college"], axis=1)
dfEliminados

,season,player_id,player_name,position,weight,standing_vertical_leap,max_vertical_leap,lane_agility_time,three_quarter_sprint
0,2001,12033,Adam Allenspach,C,259.0,28.5,31.0,11.90,3.40
1,2001,2240,Gilbert Arenas,SG,199.0,31.5,36.0,NaN,3.25
2,2001,2220,Brandon Armstrong,SG,188.0,30.0,37.0,10.91,3.20
3,2001,2203,Shane Battier,SF-PF,229.0,29.5,33.0,10.95,3.30
4,2001,12034,Cookie Belcher,SG-PG,206.0,35.0,41.5,11.26,2.91
...,...,...,...,...,...,...,...,...,...
1197,2023,1641705,Victor Wembanyama,C,NaN,NaN,NaN,NaN,NaN
1198,2023,1641727,Dariq Whitehead,SG,217.2,NaN,NaN,NaN,NaN
1199,2023,1641715,Cam Whitmore,SF,235.0,31.5,40.5,10.82,3.20
1200,2023,1630592,Jalen Wilson,SF,230.2,31.5,35.0,11.26,3.20
1201,2023,1631209,Isaiah Wong,SG,178.4,32.5,37.0,10.93,3.22

In [8]:
dfEliminados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1202 entries, 0 to 1201
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   season                  1202 non-null   int64
 1   player_id               1202 non-null   int64
 2   player_name             1202 non-null   object
 3   position                1197 non-null   object
 4   weight                  1152 non-null   float64
 5   standing_vertical_leap  1017 non-null   float64
 6   max_vertical_leap       1017 non-null   float64
 7   lane_agility_time       1008 non-null   float64
 8   three_quarter_sprint    1012 non-null   float64
dtypes: float64(5), int64(2), object(2)
memory usage: 84.6+ KB

In [9]:
ruta_guardado = "draft_stats_listo.csv" 
dfEliminados.to_csv(ruta_guardado, index=False)